# Generated by Django 3.2.7 on 2024-08-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_create_at_diary_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
