# Generated by Django 3.2.7 on 2024-08-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_rename_updated_at_diary_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
