# Generated by Django 3.2.7 on 2024-08-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_rename_update_at_diary_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
